//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reservations.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during saving reservation..
        /// </summary>
        internal static string ErrorWhileSavingReservationMsg {
            get {
                return ResourceManager.GetString("ErrorWhileSavingReservationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Table is selected. Please select a table for reservation..
        /// </summary>
        internal static string NoTableSelectedMsg {
            get {
                return ResourceManager.GetString("NoTableSelectedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation deleted successfully..
        /// </summary>
        internal static string ReservationDeleteSuccessMsg {
            get {
                return ResourceManager.GetString("ReservationDeleteSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation edited successfully..
        /// </summary>
        internal static string ReservationEditSuccessMsg {
            get {
                return ResourceManager.GetString("ReservationEditSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error loading reservation information.Please check if the Reservations XML file has been selected correctly..
        /// </summary>
        internal static string ReservationsLoadingErrorMsg {
            get {
                return ResourceManager.GetString("ReservationsLoadingErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation date or time is incorrect. Please modify the same..
        /// </summary>
        internal static string ReservationTimeErrorMsg {
            get {
                return ResourceManager.GetString("ReservationTimeErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected table(s) is already booked. Please select another table..
        /// </summary>
        internal static string SelectedTableAlreadyBookedMsg {
            get {
                return ResourceManager.GetString("SelectedTableAlreadyBookedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer party cannot be accomodated with the selected tables. Please check table selection..
        /// </summary>
        internal static string SelectedTableAndPartyMismatchMsg {
            get {
                return ResourceManager.GetString("SelectedTableAndPartyMismatchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a reservation to delete..
        /// </summary>
        internal static string SelectReservationToDeleteMsg {
            get {
                return ResourceManager.GetString("SelectReservationToDeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a reservation to edit..
        /// </summary>
        internal static string SelectReservationToEditMsg {
            get {
                return ResourceManager.GetString("SelectReservationToEditMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Tables and Reservations XML file paths using the Settings button.
        /// </summary>
        internal static string SelectXMLFilePathsMsg {
            get {
                return ResourceManager.GetString("SelectXMLFilePathsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error loading table information.Please check if the Tables XML file has been selected correctly..
        /// </summary>
        internal static string TableLoadingErrorMsg {
            get {
                return ResourceManager.GetString("TableLoadingErrorMsg", resourceCulture);
            }
        }
    }
}
